### ISSUE TITLE
Return metadata pagination information in get functions

### ISSUE THREAD

**Issue by jframi** [mverouden/brapir-v2#2]
If I understand well all the get functions have a page and pagesize parameter, and the call response is turned into a data.frame using brapi_result2df function. I am not clear though how (or if) the pagination information in the metadata section of the response is handled in this function, and if there is a way to pass it, maybe as an attribute to the resulting data.frame.

**Comment by mverouden** [comment]
Pagination has been added to the returned data.frame, when available.

Example:
```
library(brapirv2)
brapi_serverinfo_show(show = TRUE)
con <- brapi_db()$testserver
out <- brapi_get_studies(con = con)
attr(out, which = "pagination")
```
